# Generated by Django 5.1.7 on 2025-04-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vacancy_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='new',
        ),
    ]
